<a href="https://colab.research.google.com/github/Gunjari-Philip/Machine-Learning/blob/main/numpy_python.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [47]:
import numpy as np

arr1 = np.array([1,2,3,4,5])

print(arr)
print(type(arr))

[[1 2 3]
 [4 5 6]]
<class 'numpy.ndarray'>


In [48]:
arr2 = np.array([[1,2,3],[4,5,6]])
print(arr2)

[[1 2 3]
 [4 5 6]]


In [49]:
arr3 = np.array([
    [[1,2,3],[4,5,6]],
    [[1,2,3],[4,5,6]]
])
print(arr3)

[[[1 2 3]
  [4 5 6]]

 [[1 2 3]
  [4 5 6]]]


In [50]:
print(arr1.ndim)
print(arr2.ndim)
print(arr3.ndim)

1
2
3


In [51]:
arr = np.array([1, 2, 3, 4], ndmin=4)
print(arr.ndim)

4


In [52]:
print(arr1[2])

3


In [53]:
arr = np.array([[1,2,3,4,5], [6,7,8,9,10]])

print('Last element from 2nd dim: ', arr[1, -1])

Last element from 2nd dim:  10


In [54]:
arr = np.array([1, 2, 3, 4, 5, 6, 7])

print(arr[-3:-1])


[5 6]


In [55]:
arr = np.array([1, 2, 3, 4, 5, 6, 7])

print(arr[1:5:2])

[2 4]


In [56]:
arr = np.array([1, 2, 3, 4, 5, 6, 7])

print(arr[::2])

[1 3 5 7]


In [57]:
arr = np.array([[1, 2, 3, 4, 5], [6, 7, 8, 9, 10]])

print(arr[1, 1:4])


[7 8 9]


In [58]:

print(arr[0:2, 2])

print(arr[0:2, 1:4])

[3 8]
[[2 3 4]
 [7 8 9]]


In [59]:
arr = np.array(['apple', 'banana', 'cherry'])

print(arr.dtype)

<U6


In [60]:
arr = np.array([1, 2, 3, 4], dtype='S')

print(arr)
print(arr.dtype)

[b'1' b'2' b'3' b'4']
|S1


In [61]:
arr = np.array([1, 2, 3, 4], dtype='i4')

print(arr)
print(arr.dtype)

[1 2 3 4]
int32


In [62]:
arr = np.array([1.1, 2.1, 3.1])

newarr = arr.astype('i')

print(newarr)
print(newarr.dtype)

[1 2 3]
int32


In [63]:
arr = np.array([1.1, 2.1, 3.1])

newarr = arr.astype(int)

print(newarr)
print(newarr.dtype)

[1 2 3]
int64


In [64]:
arr = np.array([1, 0, 3])

newarr = arr.astype(bool)

print(newarr)
print(newarr.dtype)

[ True False  True]
bool


In [65]:
arr = np.array([1, 2, 3, 4, 5])
x = arr.copy()
arr[0] = 42

print(arr)
print(x)
#The copy should not be affected by the changes made to the original array.

[42  2  3  4  5]
[1 2 3 4 5]


In [66]:
x = arr.view()
arr[0] = 21

print(arr)
print(x)
#The view should be affected by the changes made to the original array.

[21  2  3  4  5]
[21  2  3  4  5]


In [67]:
arr = np.array([1, 2, 3, 4, 5])
x = arr.view()
x[0] = 31

print(arr)
print(x)

[31  2  3  4  5]
[31  2  3  4  5]


In [68]:
arr = np.array([1, 2, 3, 4, 5])

x = arr.copy()
y = arr.view()

print(x.base)
print(y.base)

None
[1 2 3 4 5]


In [69]:
arr = np.array([[1, 2, 3, 4], [5, 6, 7, 8]])

print(arr.shape)

(2, 4)


In [70]:
arr = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12])

newarr = arr.reshape(4, 3)

print(newarr)

[[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]]


In [71]:
arr = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12])

newarr = arr.reshape(2, 3, 2)

print(newarr)

[[[ 1  2]
  [ 3  4]
  [ 5  6]]

 [[ 7  8]
  [ 9 10]
  [11 12]]]


In [72]:

arr = np.array([1, 2, 3, 4, 5, 6, 7, 8])

print(arr.reshape(2, 4).base)
#The example above returns the original array, so it is a view.

[1 2 3 4 5 6 7 8]


In [73]:
#Convert the array into a 1D array
arr = np.array([[1, 2, 3], [4, 5, 6]])

newarr = arr.reshape(-1)

print(newarr)

[1 2 3 4 5 6]


In [74]:
#numpy works on vectors and matrices i.e feature vectors,weight matrices,bias terms,gradients
X = np.array([
    [1,2,3],
    [3,4,5]
])
print(X)

[[1 2 3]
 [3 4 5]]


In [75]:
#fast computation and it avoids slow python loops
a = np.array([1,2,3,4])
b = np.array([5,6,7,8])

result = a + b
print(result)

[ 6  8 10 12]


In [76]:
#numpy stores vecotrs or matrices in memory using ndarray
#An ndarray is a multidimentional array

arr_dim3 = np.array([
    [
        [1,2,3,4],
        [2,3,4,5]
    ]
])

arr_dim2 = np.array([
    [1,2,3,4],[5,6,7,8]
])
print(arr_dim3)
print(arr_dim3.ndim)

arr_dim1 = np.array([1,2,3,4])

print(arr_dim2)
print(arr_dim2.ndim)

print(arr_dim1)
print(arr_dim1.ndim)

[[[1 2 3 4]
  [2 3 4 5]]]
3
[[1 2 3 4]
 [5 6 7 8]]
2
[1 2 3 4]
1


In [77]:
print(arr_dim3.shape)
print(arr_dim3.ndim)
print(arr_dim3.size)
print(arr_dim3.dtype)

(1, 2, 4)
3
8
int64


**NumPy Operations**

In [78]:
#matrix multiplication
X = np.array([[1,2],
              [4,5]])
W = np.array([[1],
              [2]])

y1 = X @ W
y2 = np.dot(X,W)
print(y1)
print(y2)

[[ 5]
 [14]]
[[ 5]
 [14]]


In [79]:
#operations on different shapes

b = np.array([1,1])

print(X+b)

[[2 3]
 [5 6]]


In [80]:
#statistical functions

print(np.mean(X,axis = 0))
print(np.std(X,axis = 0))

print(np.min(X))
print(np.max(X))


[2.5 3.5]
[1.5 1.5]
1
5


In [81]:
#reshaping data
print(X.shape)
y1=X.reshape(4,1)
print(y1.shape)
y = X.flatten()
print(y.shape)

(2, 2)
(4, 1)
(4,)


In [82]:
y3 = X.reshape(-1,1) # -1 reperesents it automatically finds dimention,1 reperesents column and it will give row
print(y3.shape)

(4, 1)


In [83]:
a = np.array([1,2,3,4])      # (4,) it is 1D Array
b = np.array([[1],[2],[3],[4]])  # (4,1) it is 2D array

print(a + 10)
print(b + 10)

[11 12 13 14]
[[11]
 [12]
 [13]
 [14]]


In [84]:
print(X.T) #x transpose

[[1 4]
 [2 5]]


In [85]:
#indexing and slicing
print(X)
print(X[:,0]) #first feature

print(X[1,:]) #second sample

print(X[X>1]) #filtering, it flattens into 1D vector
np.where(X>1,X,0) #it keeps shape

[[1 2]
 [4 5]]
[1 4]
[4 5]
[2 4 5]


array([[0, 2],
       [4, 5]])

**NumPy functions**

In [86]:
w = np.zeros((3,2)) #Creates an array filled with zeros.
print(w)

[[0. 0.]
 [0. 0.]
 [0. 0.]]


In [87]:
print(np.ones((3,2))) #Creates an array filled with ones.

[[1. 1.]
 [1. 1.]
 [1. 1.]]


In [88]:
print(np.random.rand(3,2)) #generates random numbers uniformly between 0 and 1
#mean,std and dot

[[0.73199394 0.59865848]
 [0.15601864 0.15599452]
 [0.05808361 0.86617615]]


In [89]:
print(X)
print(np.argmax(X))

[[1 2]
 [4 5]]
3


In [90]:
np.random.seed(42)

W = np.random.randn(1, 1)   # weight
b = np.zeros((1,))


In [103]:
import numpy as np

# feature matrix
X = np.array([[1], [2], [3], [4], [5]])

# target vector
y = np.array([[2], [4], [6], [8], [10]])

print("X shape:", X.shape)
print("y shape:", y.shape)

np.random.seed(42)

W = np.random.randn(1, 1)
b = np.zeros((1, 1))

print("Initial weight:", W)
print("Initial bias:", b)

# forward pass
def predict(X, W, b):
    return np.dot(X, W) + b

# loss function
def mean_squared_error(y_true, y_pred):
    return np.mean((y_true - y_pred) ** 2)

# gradient computation
def compute_gradients(X, y_true, y_pred):
    n = len(X)
    dW = (-2 / n) * np.dot(X.T, (y_true - y_pred))
    db = (-2 / n) * np.sum(y_true - y_pred)
    return dW, db

# training
learning_rate = 0.01
epochs = 1000

for i in range(epochs):
    y_pred = predict(X, W, b)
    loss = mean_squared_error(y, y_pred)

    dW, db = compute_gradients(X, y, y_pred)

    W -= learning_rate * dW
    b -= learning_rate * db

    if i % 100 == 0:
        print(f"Epoch {i}, Loss: {loss:.4f}")

print("\nFinal weight:", W)
print("Final bias:", b)


X shape: (5, 1)
y shape: (5, 1)
Initial weight: [[0.49671415]]
Initial bias: [[0.]]
Epoch 0, Loss: 24.8586
Epoch 100, Loss: 0.0138
Epoch 200, Loss: 0.0070
Epoch 300, Loss: 0.0036
Epoch 400, Loss: 0.0018
Epoch 500, Loss: 0.0009
Epoch 600, Loss: 0.0005
Epoch 700, Loss: 0.0002
Epoch 800, Loss: 0.0001
Epoch 900, Loss: 0.0001

Final weight: [[1.99637734]]
Final bias: [[0.01307894]]


In [98]:
#final model parameters
print("Final Weight:", W)
print("Final Bias:", b)


Final Weight: [[1.99637734]]
Final Bias: [0.01307894]


In [99]:
X_test = np.array([[6], [7], [8]])
predictions = predict(X_test, W, b)

print("Predictions:")
print(predictions)


Predictions:
[[11.991343  ]
 [13.98772035]
 [15.98409769]]


In [102]:
#feature scaling

x_mean = np.mean(X)
x_std = np.std(X)

X_scaled = (X - x_mean) / x_std

print("Scaled feature :",X_scaled)

Scaled feature : [[-1.41421356]
 [-0.70710678]
 [ 0.        ]
 [ 0.70710678]
 [ 1.41421356]]
